### ISSUE TITLE
# bearsys Marked 2 Theme

### ISSUE THREAD

**Issue by extratone** [extratone/drafts#58]
# bearsys Marked 2 Theme
- [SnippetsLab](snippetslab://snippet/69BF6A24-6A0D-4D34-B0C4-F2884F7D3112/)
- [WTF](https://davidblue.wtf/drafts/9CC44BAE-9B47-4B39-BFA5-F65ABB87520A.html)

```css
/*
This document has been created with Marked.app http://marked2app.com
Content is property of the document author
Please leave this notice in place, along with any additional credits below.
—————————————————————
Title: BearSys
Author: David Blue
Description: A very minor modification of Brett Terpstra’s Bear theme - Avenir is replaced with SF Pro Text and Georgia is replaced with New York.
—
*/

body {
-webkit-font-smoothing: antialiased;
font-family: SF Pro Text, sans-serif;
margin: 25px 0 0;
padding: 0;
background: #fff;
color: #303030;
font-size: 14px;
line-height: 1.6
}

wrapper {
padding: 14px;  
margin: 0 auto;  
}

li {
font-size: 110%
}

li li {
font-size: 100%
}

li p {
font-size: 100%;
margin: .5em 0;
line-height: 1.4;
}

.task-list-item-checkbox {
top: 0!important;
}

h1 {
color: #000
}

h2 {
color: #111
}

h3 {
color: #111
}

h4 {
color: #111
}

h5 {
color: #111
}

h6 {
color: #111;
font-style: italic
}

p, td, div {
color: #111;
font-family: SF Pro Text, sans-serif;
word-wrap: break-word
}

a {
color: rgb(222, 84, 86);
text-decoration: none;
-webkit-transition: color .2s ease-in-out;
-moz-transition: color .2s ease-in-out;
-o-transition: color .2s ease-in-out;
-ms-transition: color .2s ease-in-out;
transition: color .2s ease-in-out
}

a:hover {
color: #3593d9
}

h1, h2, h3, h4, h5 {
margin: 2.75rem 0 2rem;
font-weight: 500;
line-height: 1.15
}

h1 {
margin-top: 0;
font-size: 2em
}

h2 {
font-size: 1.7em
}

h3 {
font-size: 1.2em
}

h4 {
font-size: 1.563em
}

h5 {
font-size: 1.25em
}

ul, ol, pre, table, blockquote {
margin-top: 2em;
margin-bottom: 2em
}

mark {
background: rgb(211, 255, 164);
}

blockquote {
padding: 0 0 0 1.5em;
margin: 2em 0 0 –1.5em;
border-left: 1px solid rgb(222, 84, 86);
}

hr {
border: none;
border-bottom: 1px solid #ddd;
margin: 3em 0;
}

ul ul, ol ol, ul ol, ol ul {
margin-top: 0;
margin-bottom: 0
}

b, strong, em, small, code {
line-height: 1
}

.footnote {
color: #0d6ea1;
font-size: .8em;
vertical-align: super
}

abbr, acronym {
border-bottom: 1px dotted #aaa
}

wrapper img {

max-width: 100%;  
height: auto  
}

dd {
font-size: 1em;
margin-bottom: 1em
}

li>p:first-of-type {
margin: 0
}

li p+p {
margin-top: 16px
}

ul, ol {
list-style-position: outside;
padding-left: 0;
}

ul ul, ul ol, ol ul, ol ol {
margin-bottom: .4em;
padding-left: 2em;
}

ul li {
list-style-type: none;
position: relative;
}

ul li:not(.task-list-item)::before {
color: rgb(222, 84, 86);
content: ‘●’;
display: inline;
font-size: 11px;
left: –20px;
position: absolute;
top: 2px;
}

ol {
counter-reset: list;
}

ol li {
counter-increment: list;
list-style-type: none;
position: relative;
} ol li:before {
color: rgb(222, 84, 86);
content: counter(list) “.”;
left:–32px;
position: absolute;
text-align: right;
width: 26px;
}

caption, col, colgroup, table, tbody, td, tfoot, th, thead, tr {
border-spacing: 0
}

table {
border: 1px solid rgba(0, 0, 0, 0.25);
border-collapse: collapse;
display: table;
empty-cells: hide;
margin: –1px 0 1.3125em;
padding: 0;
table-layout: fixed
}

caption {
display: table-caption;
font-weight: 700
}

col {
display: table-column
}

colgroup {
display: table-column-group
}

tbody {
display: table-row-group
}

tfoot {
display: table-footer-group
}

thead {
display: table-header-group
}

td, th {
display: table-cell
}

tr {
display: table-row
}

table th, table td {
font-size: 1.1em;
line-height: 1.3;
padding: .5em 1em 0
}

table thead {
background: rgba(0, 0, 0, 0.15);
border: 1px solid rgba(0, 0, 0, 0.15);
border-bottom: 1px solid rgba(0, 0, 0, 0.2)
}

table tbody {
background: rgba(0, 0, 0, 0.05)
}

table tfoot {
background: rgba(0, 0, 0, 0.15);
border: 1px solid rgba(0, 0, 0, 0.15);
border-top: 1px solid rgba(0, 0, 0, 0.2)
}

figure {
display: inline-block;
overflow: hidden;
position: relative;
margin: 1em 0 2em
}

figcaption {
font-style: italic;
text-align: center;
background: white;
color: #666
}

.poetry pre {
display: block;
font-family: NewYork-Regular, serif !important;
font-size: 110% !important;
font-style: italic;
line-height: 1.6em;
margin-left: 1em
}

.poetry pre code {
font-family: NewYork-Regular, serif !important;
word-break: break-all;
word-break: break-word;
-webkit-hyphens: auto;
-moz-hyphens: auto;
hyphens: auto;
white-space: pre-wrap
}

blockquote p {

}

sup, sub, a.footnote {
font-size: 1.4ex;
height: 0;
line-height: 1;
position: relative;
vertical-align: super
}

sub {
vertical-align: sub;
top: –1px
}

p {
font-size: 1.1429em;
line-height: 1.72em;
margin: 1.3125em 0
}

dt, th {
font-weight: 700
}

table tr:nth-child(odd), table th:nth-child(odd), table td:nth-child(odd) {
background: rgba(255, 255, 255, 0.06)
}

table tr:nth-child(even), table td:nth-child(even) {
background: rgba(200, 200, 200, 0.25)
}

@media print {
img, table, figure {
page-break-inside: avoid
}

#wrapper {  
    background: #fff;  
    color: #303030;  
    padding: 10px;  
    position: relative;  
    text-indent: 0  
}
}

@media screen {
.inverted {
background: #252a2a
}

.inverted #wrapper {  
    background: #252a2a;  
    color: #eee  
}

.inverted hr {  
    border-color: #333f40 !important  
}

.inverted p, .inverted td, .inverted li, .inverted h1, .inverted h2, .inverted h3, .inverted h4, .inverted h5, .inverted h6, .inverted th, .inverted .math, .inverted caption, .inverted dt, .inverted dd {  
    color: #eee  
}

.inverted pre {  
    background: #ccc;  
    color: #111  
}

.inverted table {  
    background: none  
}

.inverted table tr:nth-child(odd), .inverted table td:nth-child(odd) {  
    background: none  
}


::selection {  
    background: rgba(157, 193, 200, 0.5)  
}

h1::selection {  
    background-color: rgba(45, 156, 208, 0.3)  
}

h2::selection {  
    background-color: rgba(90, 182, 224, 0.3)  
}

h3::selection, h4::selection, h5::selection, h6::selection, li::selection, ol::selection {  
    background-color: rgba(133, 201, 232, 0.3)  
}

code::selection {  
    background-color: rgba(0, 0, 0, 0.7);  
    color: #eee  
}

code span::selection {  
    background-color: rgba(0, 0, 0, 0.7) !important;  
    color: #eee !important  
}

a::selection {  
    background-color: rgba(255, 230, 102, 0.2)  
}

.inverted a::selection {  
    background-color: rgba(255, 230, 102, 0.6)  
}

td::selection, th::selection, caption::selection {  
    background-color: rgba(180, 237, 95, 0.5)  
}
}

.mkstyle–swiss #wrapper aside.blurb:before {
margin-top: .7em
}
```
